name: Automated tests

on:
  workflows_dispatch:
    inputs:
      deployments_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - first_test



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: first_tests
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest



