name: Automated tests

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - first_test
          - second_test



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: first_test
        if: "github.event.inputs.logLevel == 'first_test'"
        run: pytest
      - name: second_test
        if: "github.event.inputs.logLevel == 'second_test'"
        run: pytest



